.dockerignore, .travis.yml, Dockerfile, deploy.sh, docker-compose.yml
=> Deploy to quay

Dockerfile, src/Keboola/MongoDbExtractor/MongoExportCommand.php, tests/Keboola/MongoDbExtractor/MongoExportCommandTest.php, tests/Keboola/Test/ExtractorTestCase.php
=> Mongodb clients

src/Keboola/MongoDbExtractor/ConfigDefinition.php, src/Keboola/MongoDbExtractor/MongoExportCommand.php, tests/Keboola/MongoDbExtractor/MongoExportCommandTest.php, tests/Keboola/Test/ExtractorTestCase.php
=> Sort and limit support

src/Keboola/MongoDbExtractor/ConfigDefinition.php, src/Keboola/MongoDbExtractor/MongoExportCommand.php, src/run.php, tests/Keboola/MongoDbExtractor/MongoExportCommandTest.php
- enables encrypted password
- requires both username and password or none ot them
Fixes #14
=> Better auth params handling

composer.json, composer.lock, src/Keboola/MongoDbExtractor/Application.php, src/Keboola/MongoDbExtractor/Extractor.php, src/run.php, tests/Keboola/MongoDbExtractor/ApplicationTest.php
Fixes #27 
- updated dependencies
- new application class and its usage in bootstrap file
- tests
=> Test connection action

src/Keboola/MongoDbExtractor/Application.php, src/Keboola/MongoDbExtractor/Export.php, src/Keboola/MongoDbExtractor/Extractor.php, tests/Keboola/MongoDbExtractor/ApplicationTest.php, tests/Keboola/MongoDbExtractor/ExtractorTestCase.php
- Simplified application actions
- Extractor responsible for mapping, not Export
- Exports creation moved to Extractor/extract
- New test to wrong credentials
- Simplified extractor test case
=> Refactoring due to better conection testing

src/Keboola/MongoDbExtractor/MongoExportCommandJson.php, tests/Keboola/MongoDbExtractor/MongoExportCommandJsonTest.php
1. new export (limit untouched) -> worked
2. untouched limit changed to number -> worked
3. changed limit from number back to "empty string"  -> failed
This PR fixes 3.
=> Test and fix for empty optional values

src/Keboola/MongoDbExtractor/Export.php, src/Keboola/MongoDbExtractor/MongoExportCommandJson.php, tests/Keboola/MongoDbExtractor/ExtractorTestCase.php, tests/Keboola/MongoDbExtractor/MongoExportCommandJsonTest.php
=> Line by line parsing

composer.json, composer.lock, tests/Keboola/MongoDbExtractor/ExtractorTestCase.php
=> Update csvmap library. Fix test.

README.md, composer.json, composer.lock, src/Keboola/MongoDbExtractor/Export.php, src/run.php, tests/Keboola/MongoDbExtractor/ApplicationTest.php, tests/Keboola/MongoDbExtractor/ConfigDefinitionTest.php, tests/Keboola/MongoDbExtractor/ExtractorDirectConnectionTest.php, tests/Keboola/MongoDbExtractor/ExtractorDirectConnectionWithAuthTest.php, tests/Keboola/MongoDbExtractor/ExtractorNotEnabledExportsTest.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionTest.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionWithAuthTest.php
=> Switch to json configuration format

tests/Keboola/MongoDbExtractor/ExtractorNoSpaceLeftOnDeviceTest.php
=> Add test for no space left on device

docker-compose.yml, docker/mongodb/init-auth.js, src/Keboola/MongoDbExtractor/Extractor.php, tests/Keboola/MongoDbExtractor/ExtractorDirectConnectionWithAuthTest.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionWithAuthTest.php
Fixes #71 
Changes:
- increase wait time for mongodb services (for sure)
- change password in "mongo db with auth" service to contain special characters and fail
- encode username and password when creating connection URI
=> Encode username and password in connection URI

src/run.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionTimeoutTest.php
Fixes #74 
Changes:
- Catch exception from SSH tunnel library
=> Catch also ssh exception

src/Keboola/MongoDbExtractor/Export.php
=> Remove custom logToConsoleOutput fn (use consoleOutput->writeln)

Dockerfile, composer.json, composer.lock, docker/php/php-prod.ini, docker/php/php.ini, tests/Keboola/MongoDbExtractor/ApplicationRawModeTest.php, tests/Keboola/MongoDbExtractor/ApplicationTest.php, tests/Keboola/MongoDbExtractor/ApplicationTestConnectionTest.php, tests/Keboola/MongoDbExtractor/ConfigDefinitionTest.php, tests/Keboola/MongoDbExtractor/ExtractorDirectConnectionTest.php, tests/Keboola/MongoDbExtractor/ExtractorDirectConnectionWithAuthTest.php, tests/Keboola/MongoDbExtractor/ExtractorNoSpaceLeftOnDeviceTest.php, tests/Keboola/MongoDbExtractor/ExtractorNotEnabledExportsTest.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionTest.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionTimeoutTest.php, tests/Keboola/MongoDbExtractor/ExtractorSshConnectionWithAuthTest.php, tests/Keboola/MongoDbExtractor/ExtractorTestCase.php, tests/Keboola/MongoDbExtractor/Unit/MongoExportCommandJsonTest.php
Fixes #79 
Changes:
- update to php 7.2 + update of mongodb tools to 4.0
- updated composers dependencies
- fixed code style
=> Update to php 7.2 + dependencies update

composer.json, composer.lock, tests/Keboola/MongoDbExtractor/ExtractorObjectInPrimaryKeyTest.php
Fixes: #86 
Changes:
- update keboola/csvmap to v5
- add failing test for wrong PK definition
Todo:
- update to latest keboola/csvmap
=> Non scalar value in PK should be user error

.travis.yml
Fixes #67 
Changes:
- Init configuration for travis build stages
=> Init build stages

.travis.yml
=> Run integration test job

src/Keboola/MongoDbExtractor/Export.php
=> Json Decode error handling

README.md, docker-compose.yml, tests/Keboola/MongoDbExtractor/ApplicationRawModeTest.php
Changes:
- added missing step to readme, without it build failed
- changed mongodb version `3.0` -> `3.2`
- version `3.0` not working with docker `19.03.5`
=> Initial fixes: update readme, unify Mongodb versions

.travis.yml
Changes:
- Add test job with SSH configuration
=> Add test job with SSH configuration

docker-compose.yml, src/Keboola/MongoDbExtractor/Application.php, src/Keboola/MongoDbExtractor/Config/ConfigDefinition.php, src/Keboola/MongoDbExtractor/Export.php, src/Keboola/MongoDbExtractor/ExportCommandFactory.php, src/Keboola/MongoDbExtractor/Extractor.php, src/run.php, tests/Keboola/MongoDbExtractor/ApplicationIncrementalFetchingTest.php, tests/Keboola/MongoDbExtractor/ConfigDefinitionTest.php, tests/dataset-incremental-fetching.json
Support incremental fetching - https://keboola.atlassian.net/browse/COM-119
=> support incremental fetching

src/Keboola/MongoDbExtractor/Extractor.php, tests/Keboola/MongoDbExtractor/ExtractorInvalidUriTest.php
Solving - https://keboola.atlassian.net/browse/COM-199
=> catch mongodb uri exception

src/Keboola/MongoDbExtractor/Extractor.php, tests/Keboola/MongoDbExtractor/ApplicationIncrementalFetchingTest.php
Solving - https://keboola.atlassian.net/browse/COM-242
=> Fixed clearing output state

src/Keboola/MongoDbExtractor/Export.php, tests/Keboola/MongoDbExtractor/ApplicationIncrementalFetchingTest.php
Solving - https://keboola.atlassian.net/browse/COM-240
=> throw UserException if column does not exists

src/Keboola/MongoDbExtractor/UriFactory.php, tests/Keboola/MongoDbExtractor/Unit/UriFactoryTest.php
Solving: https://keboola.atlassian.net/browse/COM-279
=> Escape authSource and database in UriFactory

README.md, composer.json, composer.lock, src/Keboola/MongoDbExtractor/Application.php, src/Keboola/MongoDbExtractor/Config/ConfigDefinition.php, src/Keboola/MongoDbExtractor/ExportCommandFactory.php, src/Keboola/MongoDbExtractor/Extractor.php, src/Keboola/MongoDbExtractor/Uri.php, src/Keboola/MongoDbExtractor/UriFactory.php, tests/Keboola/MongoDbExtractor/ApplicationTest.php, tests/Keboola/MongoDbExtractor/ApplicationTestConnectionTest.php, tests/Keboola/MongoDbExtractor/ConfigDefinitionTest.php, tests/Keboola/MongoDbExtractor/ExtractorClusterConnectionTest.php, tests/Keboola/MongoDbExtractor/ExtractorInvalidUriTest.php, tests/Keboola/MongoDbExtractor/Unit/UriFactoryTest.php
Solving: https://keboola.atlassian.net/browse/COM-278
Changes:
- Added support MongoDB connection string as connection protocol `custom_uri`.
=> Add support for custom URI

README.md, src/Keboola/MongoDbExtractor/Parser/Mapping.php, tests/Keboola/MongoDbExtractor/ApplicationIncrementalFetchingTest.php
Changes:
- Better `README.md`, Slack: https://keboola.slack.com/archives/CMTBFNLF8/p1596623614033300?thread_ts=1596618884.032900&cid=CMTBFNLF8
- Fixed date mapping backward compatibility, see: https://help.keboola.com/components/extractors/database/mongodb/#other-data-types
=> Fix date mapping backward compatibility

src/Keboola/MongoDbExtractor/Config/ConfigDefinition.php, src/Keboola/MongoDbExtractor/Export.php, src/Keboola/MongoDbExtractor/Parser/Mapping.php, tests/Keboola/MongoDbExtractor/ApplicationIncrementalFetchingTest.php, tests/Keboola/MongoDbExtractor/ConfigDefinitionTest.php, tests/dataset-incremental-fetching.json
Solving: https://keboola.atlassian.net/browse/COM-375
Slack: https://keboola.slack.com/archives/CQ1ASK06M/p1596722403018800
Changes:
- Fixed problems with `date` in `mapping`.
=> Fix problem with date in nested fields

src/Keboola/MongoDbExtractor/Export.php, tests/Keboola/MongoDbExtractor/ExtractorTestCase.php
Jira: https://keboola.atlassian.net/browse/COM-716
=> Convert CSV exception to user error

src/Keboola/MongoDbExtractor/Export.php
Jira: https://keboola.atlassian.net/browse/COM-835
=> User-friendly error message for EOF error
